### ISSUE TITLE
[[BUG] - application/x-amz-json-1.0

### ISSUE THREAD

**Issue by SalvatorePreviti** [jennyEckstein/sqslite#660]
**Is your feature request related to a problem? Please describe.**

I am still investigating but it seems that the new versions of the AWS SDK client @aws-sdk/client-sqs is sending an Unsupported Media Type application/x-amz-json-1.0 that fails with the current version.

SQSError: SQS receive message failed: Unsupported Media Type: application/x-amz-json-1.0
    at toSQSError (/x/node_modules/sqs-consumer/dist/errors.js:42:22)
    at Consumer.receiveMessage (/x/node_modules/sqs-consumer/dist/consumer.js:190:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'FST_ERR_CTP_INVALID_MEDIA_TYPE',
  statusCode: 415,
  retryable: undefined,
  service: undefined,
  fault: 'client',
  time: 2023-11-16T17:00:26.666Z
}

**Describe the solution you'd like**

Support for the new aws sdk client, and, application/x-amz-json-1.0

**Describe alternatives you've considered**

Still researching

**Additional context**

**Comment by SalvatorePreviti** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-sqs-support-json-protocol/#:~:text=New%20customers%20will%20use%20the,in%20SQS%2C%20see%20AWS%20documentation
